# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-04 16:21
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels_pun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='index',
        ),
        migrations.AddField(
            model_name='player',
            name='belief_index',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='long_reflection',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
