# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-04 20:07
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels_pun', '0004_player_display_punish_bonus_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='display_punish_bonus_result',
        ),
        migrations.AddField(
            model_name='group',
            name='display_punish_bonus_result',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
