# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-04 20:17
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels_pun', '0005_auto_20200204_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='vote',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10000, null=True, verbose_name=''),
        ),
    ]
