# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-04 20:33
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels_pun', '0007_auto_20200204_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='counter',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
