# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-03 21:59
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels_comm', '0002_player_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='role',
        ),
        migrations.AddField(
            model_name='player',
            name='chat_nickname',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
