# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-03 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels_comm', '0003_auto_20200203_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='chat_nickname',
        ),
    ]
