# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-03 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0004_session_mturk_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('condition', otree.db.models.StringField(max_length=10000, null=True)),
                ('min', otree.db.models.IntegerField(null=True)),
                ('first', otree.db.models.IntegerField(null=True)),
                ('second', otree.db.models.IntegerField(null=True)),
                ('third', otree.db.models.IntegerField(null=True)),
                ('fourth', otree.db.models.IntegerField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnaround_labels_group', to='otree.Session')),
            ],
            options={
                'db_table': 'turnaround_labels_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('label', otree.db.models.StringField(max_length=10000, null=True)),
                ('random', otree.db.models.FloatField(null=True)),
                ('round_id', otree.db.models.StringField(max_length=10000, null=True)),
                ('consent', otree.db.models.StringField(choices=[('I consent', 'I consent')], max_length=10000, null=True, verbose_name='')),
                ('paying_round_a', otree.db.models.IntegerField(null=True)),
                ('paying_round_b', otree.db.models.IntegerField(null=True)),
                ('payoff_a', otree.db.models.IntegerField(null=True)),
                ('payoff_b', otree.db.models.IntegerField(null=True)),
                ('bonus', otree.db.models.IntegerField(null=True)),
                ('round_earnings', otree.db.models.IntegerField(null=True)),
                ('practice_response1', otree.db.models.IntegerField(choices=[(1, 1)], null=True, verbose_name='')),
                ('practice_response2', otree.db.models.IntegerField(choices=[(210, 210)], null=True, verbose_name='')),
                ('practice_response3', otree.db.models.IntegerField(choices=[(0, 0)], null=True, verbose_name='')),
                ('practice_response4', otree.db.models.IntegerField(choices=[(100, 100)], null=True, verbose_name='')),
                ('practice_response5', otree.db.models.IntegerField(choices=[(0, 0)], null=True, verbose_name='')),
                ('practice_response6', otree.db.models.IntegerField(choices=[(200, 200)], null=True, verbose_name='')),
                ('practice_response_a', otree.db.models.IntegerField(null=True, verbose_name='')),
                ('practice_response_b', otree.db.models.IntegerField(null=True, verbose_name='')),
                ('practice_response_c', otree.db.models.IntegerField(null=True, verbose_name='')),
                ('true_false1', otree.db.models.StringField(choices=[('True', 'True')], max_length=10000, null=True, verbose_name='')),
                ('true_false2', otree.db.models.StringField(choices=[('True', 'True')], max_length=10000, null=True, verbose_name='')),
                ('submitted_answer1', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Earnings are public.')),
                ('submitted_answer2', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Old products have been replaced.')),
                ('submitted_answer3', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='The CEO is on vacation.')),
                ('submitted_answer4', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Inventory is full.')),
                ('is_correct1', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('is_correct2', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('is_correct3', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('is_correct4', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('total_sentences', otree.db.models.IntegerField(null=True)),
                ('min_p', otree.db.models.IntegerField(null=True)),
                ('first_p', otree.db.models.IntegerField(null=True)),
                ('second_p', otree.db.models.IntegerField(null=True)),
                ('third_p', otree.db.models.IntegerField(null=True)),
                ('fourth_p', otree.db.models.IntegerField(null=True)),
                ('reflection', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='')),
                ('guess1', otree.db.models.IntegerField(null=True)),
                ('guess2', otree.db.models.IntegerField(null=True)),
                ('guess3', otree.db.models.IntegerField(null=True)),
                ('average_guess', otree.db.models.FloatField(null=True)),
                ('index', otree.db.models.FloatField(null=True)),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='')),
                ('gender', otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Prefer not to Disclose', 'Prefer not to Disclose')], max_length=10000, null=True, verbose_name='')),
                ('race', otree.db.models.StringField(choices=[('White', 'White'), ('Black', 'Black'), ('East Asian', 'East Asian'), ('South Asian', 'South Asian'), ('Middle Eastern', 'Middle Eastern'), ('Hispanic', 'Hispanic'), ('Multi-racial', 'Multi-racial'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='')),
                ('major', otree.db.models.StringField(choices=[('Economics', 'Economics'), ('Other Social Science', 'Other Social Science'), ('Chemical/Physical/Biological Sciences', 'Chemical/Physical/Biological Sciences'), ('Engineering/Computer Science', 'Engineering/Computer Science'), ('Humanities', 'Humanities'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='')),
                ('religion', otree.db.models.StringField(choices=[('Frequently // Once a week', 'Frequently // Once a week'), ('Often // Once a month', 'Often // Once a month'), ('Sometimes // Once every few months', 'Sometimes // Once every few months'), ('Seldom // Once or twice a year', 'Seldom // Once or twice a year'), ('Never', 'Never')], max_length=10000, null=True, verbose_name='')),
                ('volunteer', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='')),
                ('donate', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='')),
                ('confirm_payment', otree.db.models.StringField(choices=[('I have confirmed that I have been given correct payment', 'I have confirmed that I have been given correct payment')], max_length=10000, null=True, verbose_name='')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turnaround_labels.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnaround_labels_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnaround_labels_player', to='otree.Session')),
            ],
            options={
                'db_table': 'turnaround_labels_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('hard_work_sum', otree.db.models.IntegerField(null=True)),
                ('optimism_sum', otree.db.models.IntegerField(null=True)),
                ('total_attitude_sum', otree.db.models.IntegerField(null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnaround_labels_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'turnaround_labels_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnaround_labels.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnaround_labels.Subsession'),
        ),
    ]
