# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-03 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='hard_work_sum',
        ),
        migrations.RemoveField(
            model_name='subsession',
            name='optimism_sum',
        ),
        migrations.RemoveField(
            model_name='subsession',
            name='total_attitude_sum',
        ),
    ]
