# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-03 15:36
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels', '0002_auto_20191003_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='condition',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
