# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-03 15:45
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels', '0003_player_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='guess1',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess2',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess3',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
    ]
