# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-03 18:34
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels', '0004_auto_20191003_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='label',
        ),
        migrations.AddField(
            model_name='player',
            name='bucket',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
