# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-09 13:23
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels', '0005_auto_20191003_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='group_label',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
