# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-11-15 15:41
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels', '0007_remove_subsession_group_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_pd_strategy',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='four_opinion',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='later_pd_strategy',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='later_second_firm_feelings',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='open_comments',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='second_firm_feelings',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='zero_opinion',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name=''),
        ),
    ]
