# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-01-22 17:02
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels', '0008_auto_20191115_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='amb1',
            field=otree.db.models.StringField(blank=True, choices=[('Bag 1 (containing 16 red balls and 4 black balls)', 'Bag 1 (containing 16 red balls and 4 black balls)'), ('Bag 2 (containing 20 balls)', 'Bag 2 (containing 20 balls)')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='amb2',
            field=otree.db.models.StringField(blank=True, choices=[('Bag 1 (containing 14 red balls and 6 black balls)', 'Bag 1 (containing 14 red balls and 6 black balls)'), ('Bag 2 (containing 20 balls)', 'Bag 2 (containing 20 balls)')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='amb3',
            field=otree.db.models.StringField(blank=True, choices=[('Bag 1 (containing 12 red balls and 8 black balls)', 'Bag 1 (containing 12 red balls and 8 black balls)'), ('Bag 2 (containing 20 balls)', 'Bag 2 (containing 20 balls)')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='amb4',
            field=otree.db.models.StringField(blank=True, choices=[('Bag 1 (containing 10 red balls and 10 black balls)', 'Bag 1 (containing 10 red balls and 10 black balls)'), ('Bag 2 (containing 20 balls)', 'Bag 2 (containing 20 balls)')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='amb5',
            field=otree.db.models.StringField(blank=True, choices=[('Bag 1 (containing 8 red balls and 12 black balls)', 'Bag 1 (containing 8 red balls and 12 black balls)'), ('Bag 2 (containing 20 balls)', 'Bag 2 (containing 20 balls)')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='amb6',
            field=otree.db.models.StringField(blank=True, choices=[('Bag 1 (containing 6 red balls and 14 black balls)', 'Bag 1 (containing 6 red balls and 14 black balls)'), ('Bag 2 (containing 20 balls)', 'Bag 2 (containing 20 balls)')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='amb7',
            field=otree.db.models.StringField(blank=True, choices=[('Bag 1 (containing 4 red balls and 16 black balls)', 'Bag 1 (containing 4 red balls and 16 black balls)'), ('Bag 2 (containing 20 balls)', 'Bag 2 (containing 20 balls)')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='amb_payoff',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='amb_payoff_str',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='debrief_1',
            field=otree.db.models.StringField(choices=[('Strategy', 'Strategy'), ('Operations', 'Operations'), ('Finance', 'Finance')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='debrief_2',
            field=otree.db.models.StringField(choices=[('Number of Sentences Typed', 'Number of Sentences Typed'), ('Charitable Incentives', 'Charitable Incentives'), ('Group Size', 'Group Size')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='debrief_3',
            field=otree.db.models.StringField(choices=[('Self-Payment', 'Self-Payment'), ('Charity Payment', 'Charity Payment'), ('Those sorted by initial beliefs and actions', 'Those sorted by initial beliefs and actions')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='debrief_4',
            field=otree.db.models.StringField(choices=[('Those not sorted by initial beliefs and actions', 'Those not sorted by initial beliefs and actions'), ('Charity Payment', 'Charity Payment'), ('Group Size', 'Group Size')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='debrief_5',
            field=otree.db.models.StringField(choices=[('Groups with individuals with initial positive beliefs and actions will coordinate better in the “turnaround” period compared to those who are not sorted based on their initial beliefs and actions.', 'Groups with individuals with initial positive beliefs and actions will coordinate better in the “turnaround” period compared to those who are not sorted based on their initial beliefs and actions.'), ('Individuals in the treatment group will decide to stop playing in the middle of the experiment because they are ethically disturbed by the game.', 'Individuals in the treatment group will decide to stop playing in the middle of the experiment because they are ethically disturbed by the game.'), ('Individuals will be more likely to choose a job with an NGO following the experiment', 'Individuals will be more likely to choose a job with an NGO following the experiment')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='debrief_6',
            field=otree.db.models.StringField(choices=[('Economics experiments are always only a half an hour long, while psychology experiments can be of any length.', 'Economics experiments are always only a half an hour long, while psychology experiments can be of any length.'), ('Economics experiments are always incentivized and do not practice deception, and psychology experiments may involve deception and are often not incentivized.', 'Economics experiments are always incentivized and do not practice deception, and psychology experiments may involve deception and are often not incentivized.'), ('Economics experiments are always about financial markets, whereas psychology experiments are always about individual mental processes.', 'Economics experiments are always about financial markets, whereas psychology experiments are always about individual mental processes.')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='risk1',
            field=otree.db.models.StringField(blank=True, choices=[('$7 for certain', '$7 for certain'), ('$10 with probability 50%, $2 with probability 50%', '$10 with probability 50%, $2 with probability 50%')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='risk2',
            field=otree.db.models.StringField(blank=True, choices=[('$6 for certain', '$6 for certain'), ('$10 with probability 50%, $2 with probability 50%', '$10 with probability 50%, $2 with probability 50%')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='risk3',
            field=otree.db.models.StringField(blank=True, choices=[('$5 for certain', '$5 for certain'), ('$10 with probability, $2 with probability 50%', '$10 with probability, $2 with probability 50%')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='risk4',
            field=otree.db.models.StringField(blank=True, choices=[('$4 for certain', '$4 for certain'), ('$10 with probability 50%, $2 with probability 50%', '$10 with probability 50%, $2 with probability 50%')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='risk5',
            field=otree.db.models.StringField(blank=True, choices=[('$3 for certain', '$3 for certain'), ('$10 with probability 50%, $2 with probability 50%', '$10 with probability 50%, $2 with probability 50%')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='risk_payoff',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='risk_payoff_str',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='confirm_payment',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name=''),
        ),
    ]
