# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-01-28 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels', '0010_auto_20200128_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='manip_1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='manip_2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='manip_3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='manip_4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='manip_5',
        ),
    ]
