# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-01-28 19:12
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels', '0011_auto_20200128_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='payoff_display_str',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
