# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-01-28 21:09
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaround_labels', '0012_player_payoff_display_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='major',
        ),
        migrations.RemoveField(
            model_name='player',
            name='religion',
        ),
        migrations.AddField(
            model_name='player',
            name='belief',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='debrief_1',
            field=otree.db.models.StringField(choices=[('A', 'A')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='debrief_2',
            field=otree.db.models.StringField(choices=[('A', 'A')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='debrief_3',
            field=otree.db.models.StringField(choices=[('C', 'C')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='debrief_4',
            field=otree.db.models.StringField(choices=[('A', 'A')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='debrief_5',
            field=otree.db.models.StringField(choices=[('A', 'A')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='debrief_6',
            field=otree.db.models.StringField(choices=[('B', 'B')], max_length=10000, null=True, verbose_name=''),
        ),
    ]
