# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-18 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otree', '0002_session_mturk_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='mturk_expiration',
        ),
    ]
