# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-24 17:18
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('otree', '0003_remove_session_mturk_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mturk_expiration',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
